[package]
name = "chatgpt_voxel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = "0.9.1"
bracket-noise = "0.8.7"
dolly = "0.4.0"